language: python
branches:
  only:
    - master
env:
  global:
    secure: "Ja3c+ByWnSnev4O7TO2nRc29L2wUpWD6MGFC0pMImS1mtIvUyANADeQnZQVgFbrCdSCNFPhcDE4lmRmEqKa2GiA7+BdyV7vQCKpHNmuxl/C3lr3a16GGz8LCwvxmMDkJhgIYexAtgMWanZoVPbu6vy8CSYzm9N4R8JG5kZ8k50s="
install:
  - pip install ghp-import
script:
  - make develop public gh-pages-commit gh-pages-push
